import type { Member, ChatMessage, ActivityEvent, Task, ProjectActivity, TodoItem, Annotation, SystemChatMessage, SystemEventType, ProjectActivityType, MemberRole, ActivityPriority } from './types';

export const MEMBERS: Member[] = [
  {
    id: 'm1',
    name: 'Alex Chen',
    initials: 'AC',
    color1: '#06b6d4',
    color2: '#3b82f6',
    isOnline: true,
    role: 'director',
    roleLabel: '导演',
  },
  {
    id: 'm2',
    name: 'Sam Liu',
    initials: 'SL',
    color1: '#8b5cf6',
    color2: '#a855f7',
    isOnline: true,
    role: 'editor',
    roleLabel: '剪辑',
  },
  {
    id: 'm3',
    name: 'Jordan Wu',
    initials: 'JW',
    color1: '#f97316',
    color2: '#ec4899',
    isOnline: true,
    role: 'designer',
    roleLabel: '视觉',
  },
  {
    id: 'm4',
    name: 'Casey Mo',
    initials: 'CM',
    color1: '#10b981',
    color2: '#14b8a6',
    isOnline: false,
    role: 'writer',
    roleLabel: '编剧',
  },
];

export const CHAT_MESSAGES: ChatMessage[] = [
  // ── Yesterday ─────────────────────────────────────────────────────────────
  {
    id: 'sys_a1',
    type: 'system',
    systemType: 'member_joined',
    authorId: 'm3',
    description: '加入了项目',
    time: '09:15',
    date: 'yesterday',
  },
  {
    id: 'c1',
    type: 'user',
    senderId: 'm4',
    content: '大家好，我是编剧 Casey，今天开始正式参与这个项目 👋',
    time: '09:20',
    date: 'yesterday',
  },
  {
    id: 'c2',
    type: 'user',
    senderId: 'm1',
    content: '欢迎！剧本大纲已经在共享文件夹了，有问题随时说',
    time: '09:23',
    date: 'yesterday',
  },
  {
    id: 'sys_a2',
    type: 'system',
    systemType: 'asset_uploaded',
    authorId: 'm1',
    description: '上传了素材',
    target: 'script_outline_v1.pdf',
    time: '09:25',
    date: 'yesterday',
  },
  {
    id: 'c3',
    type: 'user',
    senderId: 'm2',
    content: '初剪版本完成了，大概 18 分钟。@导演 可以先看一下整体节奏',
    time: '16:30',
    date: 'yesterday',
    reactions: [{ emoji: '👀', count: 2 }],
  },
  {
    id: 'c4',
    type: 'user',
    senderId: 'm3',
    content: '颜色分级方案我做了三个版本，明天演示给大家看',
    time: '17:45',
    date: 'yesterday',
  },
  {
    id: 'sys_a3',
    type: 'system',
    systemType: 'version_saved',
    authorId: 'm2',
    description: '保存了新版本',
    target: 'v1.0 · 初剪',
    time: '18:00',
    date: 'yesterday',
  },

  // ── Today ─────────────────────────────────────────────────────────────────
  {
    id: 'c5',
    type: 'user',
    senderId: 'm1',
    content: '第二幕的过渡需要更流畅一些，目前感觉有点割裂',
    time: '10:24',
    date: 'today',
  },
  {
    id: 'c6',
    type: 'user',
    senderId: 'm2',
    content: '我已经调整了转场时长，从 0.8s 改为 1.2s，可以看一下效果',
    time: '10:31',
    date: 'today',
    reactions: [{ emoji: '👍', count: 2 }],
  },
  {
    id: 'c7',
    type: 'user',
    senderId: 'm2',
    content: '渲染预览已经放到素材库了',
    time: '10:32',
    date: 'today',
  },
  {
    id: 'sys_a4',
    type: 'system',
    systemType: 'version_saved',
    authorId: 'm3',
    description: '保存了新版本',
    target: 'v2.4 · 色彩校正',
    time: '10:45',
    date: 'today',
  },
  {
    id: 'c8',
    type: 'user',
    senderId: 'm3',
    content: '配色方案更新了，主色调往暖色偏移，整体氛围更沉稳一些',
    time: '11:00',
    date: 'today',
    reactions: [{ emoji: '🎨', count: 1 }],
  },
  {
    id: 'c9',
    type: 'user',
    senderId: 'm4',
    content: '剧本第三场的对白我修改了，节奏感好多了，请大家审阅',
    time: '11:02',
    date: 'today',
    reactions: [
      { emoji: '🔥', count: 1 },
      { emoji: '✅', count: 2 },
    ],
  },
  {
    id: 'sys_a5',
    type: 'system',
    systemType: 'task_completed',
    authorId: 'm4',
    description: '完成了任务',
    target: '剧本 v2.3 修订',
    time: '11:03',
    date: 'today',
  },
  {
    id: 'c10',
    type: 'user',
    senderId: 'm1',
    content: '节奏比之前自然多了 👍  @剪辑 第四场的音效还需要再对一下时间轴',
    time: '11:15',
    date: 'today',
  },
  {
    id: 'c11',
    type: 'user',
    senderId: 'm2',
    content: '音效这边我来处理，下午可以出一版给大家看',
    time: '11:20',
    date: 'today',
  },
  {
    id: 'sys_a6',
    type: 'system',
    systemType: 'asset_uploaded',
    authorId: 'm3',
    description: '上传了素材',
    target: 'color_palette_v3.png',
    time: '13:50',
    date: 'today',
  },
  {
    id: 'c12',
    type: 'user',
    senderId: 'm3',
    content: '字幕字体确定用 Noto Sans 吗？还是要换成更有设计感的？',
    time: '14:05',
    date: 'today',
  },
  {
    id: 'c13',
    type: 'user',
    senderId: 'm1',
    content: '先用 Noto Sans，后期迭代，不要卡在这里',
    time: '14:08',
    date: 'today',
  },
  {
    id: 'c14',
    type: 'user',
    senderId: 'm4',
    content: '最终剧本我会在今天内出 v3.0，包含所有修订意见',
    time: '15:30',
    date: 'today',
    reactions: [{ emoji: '⏰', count: 1 }],
  },
];

export const ACTIVITIES: ActivityEvent[] = [
  {
    id: 'a1',
    type: 'upload',
    authorId: 'm1',
    description: '上传了素材',
    target: 'main_scene_03.mp4',
    timestamp: '刚刚',
  },
  {
    id: 'a2',
    type: 'edit',
    authorId: 'm2',
    description: '编辑了分镜',
    target: '第 12 帧',
    timestamp: '5 分钟前',
  },
  {
    id: 'a3',
    type: 'version',
    authorId: 'm3',
    description: '保存了新版本',
    target: 'v2.4 · 色彩校正',
    timestamp: '23 分钟前',
  },
  {
    id: 'a4',
    type: 'task',
    authorId: 'm4',
    description: '完成了任务',
    target: '剧本 v2.3 修订',
    timestamp: '1 小时前',
  },
  {
    id: 'a5',
    type: 'approve',
    authorId: 'm1',
    description: '批准了分镜',
    target: '第一幕 · 全部帧',
    timestamp: '2 小时前',
  },
  {
    id: 'a6',
    type: 'comment',
    authorId: 'm2',
    description: '在时间轴上添加了批注',
    target: '00:02:34',
    timestamp: '3 小时前',
  },
  {
    id: 'a7',
    type: 'join',
    authorId: 'm3',
    description: '加入了项目',
    timestamp: '昨天',
  },
  {
    id: 'a8',
    type: 'edit',
    authorId: 'm4',
    description: '更新了剧本',
    target: '第三幕 · 场景 7',
    timestamp: '昨天',
  },
];

export const TASKS: Task[] = [
  {
    id: 't1',
    title: '完成第三幕分镜绘制',
    assigneeId: 'm1',
    status: 'inProgress',
    priority: 'high',
    dueDate: '3/13',
    tags: ['分镜'],
  },
  {
    id: 't2',
    title: '修改音效时间轴对齐',
    assigneeId: 'm2',
    status: 'todo',
    priority: 'medium',
    dueDate: '3/14',
    tags: ['音效'],
  },
  {
    id: 't3',
    title: 'UI 整体色调统一检查',
    assigneeId: 'm3',
    status: 'review',
    priority: 'medium',
    tags: ['视觉'],
  },
  {
    id: 't4',
    title: '审阅并定稿最终剧本',
    assigneeId: 'm4',
    status: 'todo',
    priority: 'urgent',
    dueDate: '3/12',
    tags: ['剧本'],
  },
  {
    id: 't5',
    title: '导出预览版本 v2.5',
    assigneeId: 'm1',
    status: 'done',
    priority: 'high',
    tags: ['导出'],
  },
  {
    id: 't6',
    title: '角色动效制作 · 第二幕',
    assigneeId: 'm3',
    status: 'inProgress',
    priority: 'medium',
    dueDate: '3/15',
    tags: ['动效'],
  },
];

export const CURRENT_USER_ID = 'm1';

// ── Project Activities (rich activity stream) ─────────────────────────────────

// ── Todo items ────────────────────────────────────────────────────────────────

export const TODO_ITEMS: TodoItem[] = [
  // ── High priority ──────────────────────────────────────────────────────────
  {
    id: 'td1',
    title: '第三幕镜头顺序重排',
    description: '根据导演最新意见调整分镜排列，重新标注镜头编号与衔接关系',
    assigneeId: 'm1',
    status: 'in_progress',
    priority: 'high',
    relatedShotId: 'shot_act3_01',
    dueTime: '今天 18:00',
    tags: ['分镜'],
  },
  {
    id: 'td2',
    title: '主配乐最终混音确认',
    description: '与导演对齐混音方案，确认情绪节奏与画面匹配，输出混音报告',
    assigneeId: 'm2',
    status: 'todo',
    priority: 'high',
    relatedShotId: 'shot_act2_05',
    dueTime: '今天 20:00',
    tags: ['配乐'],
  },
  {
    id: 'td3',
    title: '终稿剧本定稿审批',
    description: '第三幕完整修订版本需导演最终审阅签字，解锁后续制作环节',
    assigneeId: 'm4',
    status: 'todo',
    priority: 'high',
    relatedShotId: 'shot_act3_01',
    dueTime: '已超期',
    tags: ['剧本'],
  },
  // ── Medium priority ────────────────────────────────────────────────────────
  {
    id: 'td4',
    title: '第一幕分镜逐帧复核',
    description: '核查景别、运镜是否符合视觉风格指南，标注需修改的帧',
    assigneeId: 'm1',
    status: 'in_progress',
    priority: 'medium',
    relatedShotId: 'shot_act1_12',
    dueTime: '明天 10:00',
    tags: ['分镜'],
  },
  {
    id: 'td5',
    title: '音效时间轴精对',
    description: '00:02:34 段落环境音与画面精准同步，调整至帧级误差',
    assigneeId: 'm2',
    status: 'todo',
    priority: 'medium',
    relatedShotId: 'shot_act2_04',
    dueTime: '3/14 截止',
    tags: ['音效'],
  },
  {
    id: 'td6',
    title: '字幕样式最终验收',
    description: '字体规格、间距、安全框全面验收，输出字幕规范文档',
    assigneeId: 'm3',
    status: 'in_progress',
    priority: 'medium',
    relatedShotId: undefined,
    dueTime: '3/14 截止',
    tags: ['视觉'],
  },
  {
    id: 'td7',
    title: '全片色彩一致性检查',
    description: '比对各幕 LUT 参数一致性，确保风格统一，输出比对报告',
    assigneeId: 'm3',
    status: 'todo',
    priority: 'medium',
    relatedShotId: undefined,
    dueTime: '3/15 截止',
    tags: ['视觉'],
  },
  // ── Low priority ───────────────────────────────────────────────────────────
  {
    id: 'td8',
    title: '导出预览版本 v3.0',
    description: 'H.264 1080p 含字幕轨道，上传共享空间并通知全员',
    assigneeId: 'm1',
    status: 'done',
    priority: 'low',
    relatedShotId: undefined,
    dueTime: '3/12 已完成',
    tags: ['导出'],
  },
  {
    id: 'td9',
    title: '各场景时长统计表',
    description: '整理每个场景的精确时长，填入制作进度追踪表格',
    assigneeId: 'm2',
    status: 'done',
    priority: 'low',
    relatedShotId: undefined,
    dueTime: '3/11 已完成',
    tags: ['剪辑'],
  },
  {
    id: 'td10',
    title: '备用台词整理归档',
    description: '将修改过程中删减的备用台词整理成文档，归档备查',
    assigneeId: 'm4',
    status: 'todo',
    priority: 'low',
    relatedShotId: undefined,
    dueTime: '3/18 截止',
    tags: ['剧本'],
  },
];

export const PROJECT_ACTIVITIES: ProjectActivity[] = [
  // ── High priority ──────────────────────────────────────────────────────────
  {
    id: 'act1',
    actionType: 'storyboard_approved',
    title: '全片分镜最终批准',
    summary: '导演批准了全部 32 个镜头的分镜稿，项目可进入动画制作阶段',
    operatorId: 'm1',
    relatedShotId: 'shot_all',
    timestamp: '2026-03-11T15:40:00',
    timeAgo: '3 分钟前',
    impactRoles: ['editor', 'designer', 'writer'],
    priority: 'high',
    stage: 'storyboard',
  },
  {
    id: 'act2',
    actionType: 'script_update',
    title: '剧本第三幕大幅修订',
    summary: '对白节奏重构，删除冗余场景 2 处，整体时长缩减约 2 分钟',
    operatorId: 'm4',
    relatedShotId: 'shot_act3_01',
    timestamp: '2026-03-11T14:55:00',
    timeAgo: '48 分钟前',
    impactRoles: ['director', 'editor'],
    priority: 'high',
    stage: 'script',
  },
  {
    id: 'act3',
    actionType: 'soundtrack_replaced',
    title: '主配乐全面替换',
    summary: '第二幕背景音乐替换为新版本，BPM 从 90 调整为 108，情绪张力更强',
    operatorId: 'm2',
    relatedShotId: 'shot_act2_05',
    timestamp: '2026-03-11T14:20:00',
    timeAgo: '1 小时前',
    impactRoles: ['director', 'designer'],
    priority: 'high',
    stage: 'editor',
  },

  // ── Medium priority ────────────────────────────────────────────────────────
  {
    id: 'act4',
    actionType: 'shot_added',
    title: '新增过渡镜头 · 第二幕',
    summary: '在场景 5→6 之间插入 3s 空景过渡镜头，加强叙事节奏感',
    operatorId: 'm2',
    relatedShotId: 'shot_act2_06',
    timestamp: '2026-03-11T13:45:00',
    timeAgo: '2 小时前',
    impactRoles: ['director', 'designer'],
    priority: 'medium',
    stage: 'storyboard',
  },
  {
    id: 'act5',
    actionType: 'style_changed',
    title: '全局视觉色调调整',
    summary: '主色调从冷蓝转向暖橙，增强情感表达，已更新全局 LUT 文件',
    operatorId: 'm3',
    relatedShotId: undefined,
    timestamp: '2026-03-11T13:00:00',
    timeAgo: '2.5 小时前',
    impactRoles: ['director', 'editor'],
    priority: 'medium',
    stage: 'style',
  },
  {
    id: 'act6',
    actionType: 'storyboard_approved',
    title: '第一幕分镜通过审核',
    summary: '共 12 个镜头全部通过审核，景别与运镜符合剧本要求',
    operatorId: 'm1',
    relatedShotId: 'shot_act1_12',
    timestamp: '2026-03-11T11:20:00',
    timeAgo: '4 小时前',
    impactRoles: ['editor', 'designer'],
    priority: 'medium',
    stage: 'storyboard',
  },
  {
    id: 'act7',
    actionType: 'script_update',
    title: '场景舞台说明补充',
    summary: '补充了第二幕各场景的灯光备注与镜头语言说明，涉及 6 个场景',
    operatorId: 'm4',
    relatedShotId: 'shot_act2_01',
    timestamp: '2026-03-11T10:30:00',
    timeAgo: '5 小时前',
    impactRoles: ['director', 'designer'],
    priority: 'medium',
    stage: 'script',
  },
  {
    id: 'act11',
    actionType: 'shot_added',
    title: '新增片尾字幕镜头',
    summary: '添加片尾 staff roll 镜头，时长约 45s，使用淡出转场',
    operatorId: 'm1',
    relatedShotId: 'shot_credits',
    timestamp: '2026-03-10T14:30:00',
    timeAgo: '昨天',
    impactRoles: ['editor', 'designer'],
    priority: 'medium',
    stage: 'storyboard',
  },

  // ── Low priority ───────────────────────────────────────────────────────────
  {
    id: 'act8',
    actionType: 'asset_uploaded',
    title: '颜色参考素材上传',
    summary: '新增 8 张电影色调参考图，存放于 /assets/color-ref/ 目录',
    operatorId: 'm3',
    relatedShotId: undefined,
    timestamp: '2026-03-11T10:00:00',
    timeAgo: '5.5 小时前',
    impactRoles: ['designer'],
    priority: 'low',
    stage: 'style',
  },
  {
    id: 'act9',
    actionType: 'member_comment',
    title: '时间轴批注 · 音效问题',
    summary: '在 00:02:34 处标记音效电平问题，建议环境音降低 -3dB',
    operatorId: 'm2',
    relatedShotId: 'shot_act2_04',
    timestamp: '2026-03-11T09:50:00',
    timeAgo: '昨天',
    impactRoles: ['editor'],
    priority: 'low',
    stage: 'editor',
  },
  {
    id: 'act10',
    actionType: 'style_changed',
    title: '字幕样式细节微调',
    summary: '字号从 24px 调整为 22px，字符间距增加 0.5em，视觉更精细',
    operatorId: 'm3',
    relatedShotId: undefined,
    timestamp: '2026-03-10T16:00:00',
    timeAgo: '昨天',
    impactRoles: ['designer'],
    priority: 'low',
    stage: 'style',
  },
  {
    id: 'act12',
    actionType: 'asset_uploaded',
    title: '城市夜景背景参考',
    summary: '上传 12 张城市夜景参考照片集，用于第三幕背景设计参考',
    operatorId: 'm1',
    relatedShotId: undefined,
    timestamp: '2026-03-10T10:00:00',
    timeAgo: '昨天',
    impactRoles: ['designer'],
    priority: 'low',
    stage: 'script',
  },
];

// ── Shot Annotations ──────────────────────────────────────────────────────────

export const SHOT_ANNOTATIONS: Annotation[] = [
  // Shot s1 · 城市夜景（已批准）
  {
    id: 'an1', shotId: 's1', authorId: 'm1',
    content: '高光区域稍显过曝，建议压低约 15% 以保留天空细节层次',
    time: '2小时前', status: 'resolved', position: { x: 73, y: 24 },
  },
  {
    id: 'an2', shotId: 's1', authorId: 'm3',
    content: '左侧建筑群霓虹颜色饱和度不足，提升鲜艳度可以更好地营造赛博朋克氛围',
    time: '1小时前', status: 'open', position: { x: 26, y: 64 },
  },

  // Shot s2 · 主角登场（已批准）
  {
    id: 'an3', shotId: 's2', authorId: 'm2',
    content: '逆光发丝光晕效果很好，可以稍微增强一点让人物轮廓更有质感',
    time: '3小时前', status: 'resolved', position: { x: 52, y: 36 },
  },

  // Shot s3 · 对话近景（已批准）
  {
    id: 'an4', shotId: 's3', authorId: 'm1',
    content: '主角说话时有轻微镜头抖动，需要稳定处理或添加数字防抖',
    time: '45分钟前', status: 'open', position: { x: 30, y: 32 },
  },
  {
    id: 'an5', shotId: 's3', authorId: 'm3',
    content: '两人景深不一致，背景虚化程度需要统一，否则剪辑时会显突兀',
    time: '30分钟前', status: 'in_progress', position: { x: 68, y: 55 },
  },
  {
    id: 'an6', shotId: 's3', authorId: 'm4',
    content: '对白节奏偏沉，建议加快语速或压缩时长，当前版本情绪节奏略松',
    time: '15分钟前', status: 'open', position: { x: 46, y: 76 },
  },

  // Shot s4 · 动作序列（审核中）
  {
    id: 'an7', shotId: 's4', authorId: 'm2',
    content: '第 3 到第 4 个剪辑点需要对准音乐节拍，目前差约 2 帧，听感不对',
    time: '1小时前', status: 'in_progress', position: { x: 27, y: 42 },
  },
  {
    id: 'an8', shotId: 's4', authorId: 'm1',
    content: '整体剪辑节奏出色，但最后收尾一刀建议换成更有力的动作关键帧',
    time: '40分钟前', status: 'open', position: { x: 71, y: 27 },
  },

  // Shot s5 · 情绪过渡（进行中）
  {
    id: 'an9', shotId: 's5', authorId: 'm4',
    content: '空景停留时间稍长，可以从 6 秒压缩至 4 秒，节奏更紧凑且情绪张力更强',
    time: '20分钟前', status: 'open', position: { x: 50, y: 45 },
  },

  // Shot s6 · 情绪高点（进行中）
  {
    id: 'an10', shotId: 's6', authorId: 'm1',
    content: '曝光上升速度过快，建议改为 30 帧缓入，当前 15 帧显得太突兀失真',
    time: '1小时前', status: 'open', position: { x: 62, y: 28 },
  },
  {
    id: 'an11', shotId: 's6', authorId: 'm3',
    content: '背景虚化层次可以进一步加深，主角与背景的焦点分离感需要更强',
    time: '35分钟前', status: 'in_progress', position: { x: 33, y: 66 },
  },

  // Shot s7 · 反转揭示（待处理）
  {
    id: 'an12', shotId: 's7', authorId: 'm4',
    content: '参考第 3 幕概念图的机位设定，摄像机需从低角度仰拍以强化压迫感',
    time: '刚刚', status: 'open', position: { x: 55, y: 42 },
  },
];

// ── Mock system events (用于"模拟关键改动"演示按钮) ────────────────────────────

export interface MockSystemEventTemplate {
  /** 事件标签，显示在按钮 tooltip */
  label: string;
  activity: Omit<ProjectActivity, 'id' | 'timestamp'>;
  systemMsg: Omit<SystemChatMessage, 'id' | 'time' | 'date'>;
}

export const MOCK_SYSTEM_EVENTS: MockSystemEventTemplate[] = [
  {
    label: '编导更新了 Shot 2 脚本描述',
    activity: {
      actionType: 'script_update' as ProjectActivityType,
      title: 'Shot 2 脚本描述已更新',
      summary: '编导调整了 Shot 2 的对话节奏与叙事逻辑，新增主角入场前的内心独白片段',
      operatorId: 'm1',
      relatedShotId: 's2',
      timeAgo: '刚刚',
      impactRoles: ['editor', 'writer'] as MemberRole[],
      priority: 'high' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'milestone' as SystemEventType,
      description: '更新了 Shot 2 对话节奏，新增主角内心独白 2 行',
      authorId: 'm1',
      target: 'Shot 2 · 主角登场',
    },
  },
  {
    label: '视觉师替换了 Shot 4 的参考图',
    activity: {
      actionType: 'asset_uploaded' as ProjectActivityType,
      title: 'Shot 4 视觉参考图已替换',
      summary: '视觉师上传了新的屋顶动作戏情绪参考板，强化夜间霓虹与强光对比',
      operatorId: 'm3',
      relatedShotId: 's4',
      timeAgo: '刚刚',
      impactRoles: ['director', 'editor'] as MemberRole[],
      priority: 'medium' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'asset_uploaded' as SystemEventType,
      description: '上传了新版 Shot 4 情绪参考板，强化霓虹高对比风格',
      authorId: 'm3',
      target: 'shot4_moodboard_v2.jpg',
    },
  },
  {
    label: '剪辑师调整了结尾转场',
    activity: {
      actionType: 'style_changed' as ProjectActivityType,
      title: '结尾转场风格已调整',
      summary: '剪辑师将 Shot 7→8 之间的硬切改为 24 帧慢溶，结合配乐节奏更具余韵',
      operatorId: 'm2',
      relatedShotId: 's8',
      timeAgo: '刚刚',
      impactRoles: ['director', 'designer'] as MemberRole[],
      priority: 'high' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'version_saved' as SystemEventType,
      description: '调整了 Shot 7→8 转场，硬切改为 24 帧慢溶',
      authorId: 'm2',
      target: 'timeline_v3.4',
    },
  },
  {
    label: 'AI Director 对 Shot 1 给出优化建议',
    activity: {
      actionType: 'member_comment' as ProjectActivityType,
      title: 'AI Director 发出构图优化建议',
      summary: 'AI Director 建议将 Shot 1 地平线调整至黄金分割点，可增强画面张力与开场仪式感',
      operatorId: 'm1',
      relatedShotId: 's1',
      timeAgo: '刚刚',
      impactRoles: ['director', 'designer'] as MemberRole[],
      priority: 'high' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'milestone' as SystemEventType,
      description: '为 Shot 1 生成了构图优化报告，建议黄金分割比例重构',
      target: 'Shot 1 构图分析 v1.2',
    },
  },
  {
    label: '编剧完成了第三幕台词修订',
    activity: {
      actionType: 'script_update' as ProjectActivityType,
      title: '第三幕台词修订完成',
      summary: '编剧完成了第三幕完整修订，共改动 12 处台词节点，核心冲突场景戏剧张力提升',
      operatorId: 'm4',
      relatedShotId: 's7',
      timeAgo: '刚刚',
      impactRoles: ['director', 'editor', 'designer'] as MemberRole[],
      priority: 'high' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'version_saved' as SystemEventType,
      description: '提交了第三幕台词完整修订稿，共 12 处改动',
      authorId: 'm4',
      target: 'script_act3_final.md',
    },
  },
  {
    label: '导演批准了故事板第二章',
    activity: {
      actionType: 'storyboard_approved' as ProjectActivityType,
      title: '故事板第二章批准通过',
      summary: '导演确认第二章全部 3 个分镜，画面风格与节奏符合创作意图，正式进入制作阶段',
      operatorId: 'm1',
      relatedShotId: 's4',
      timeAgo: '刚刚',
      impactRoles: ['editor', 'designer'] as MemberRole[],
      priority: 'medium' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'milestone' as SystemEventType,
      description: '批准了故事板第二章全部分镜，进入制作阶段',
      authorId: 'm1',
    },
  },
  {
    label: '配乐师替换了高潮段落音轨',
    activity: {
      actionType: 'soundtrack_replaced' as ProjectActivityType,
      title: '高潮段落配乐已替换',
      summary: '剪辑师上传了新版高潮配乐，BPM 调整至 128，情绪强度提升约 20%，与画面节拍更紧密',
      operatorId: 'm2',
      relatedShotId: 's6',
      timeAgo: '刚刚',
      impactRoles: ['director', 'designer'] as MemberRole[],
      priority: 'high' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'asset_uploaded' as SystemEventType,
      description: '上传了新版高潮配乐，BPM 128，情绪强度 +20%',
      authorId: 'm2',
      target: 'climax_v3.mp3',
    },
  },
  {
    label: '视觉师完成了 Shot 5 情绪调色',
    activity: {
      actionType: 'style_changed' as ProjectActivityType,
      title: 'Shot 5 情绪调色已完成',
      summary: '视觉师完成 Shot 5 冷调情绪调色，蓝绿色彩倾向增强留白感，与前后情绪过渡自然衔接',
      operatorId: 'm3',
      relatedShotId: 's5',
      timeAgo: '刚刚',
      impactRoles: ['director', 'editor'] as MemberRole[],
      priority: 'medium' as ActivityPriority,
    },
    systemMsg: {
      type: 'system' as const,
      systemType: 'version_saved' as SystemEventType,
      description: '完成了 Shot 5 冷调情绪调色，蓝绿色彩倾向增强留白感',
      authorId: 'm3',
      target: 'shot5_color_v2.lut',
    },
  },
];
